### ISSUE TITLE
Trigger all validation rules at once

### ISSUE THREAD

**Issue by tdhung80** [wsmd/react-use-form-state#57] opened 2019-04-22 09:17 UTC
Hi,

At this moment, user needs to visit a field at least once or that would not be reported as an error. How could i manually perform a validation on all fields before/after render?

My Bests,
Hung Tran

**Comment by danielbuechele** [comment] 2019-04-27 22:28
I would like to validate all inputs as soon as they are rendered. However, the `validate` method requires an event target (a reference to the input element). I don't have a good idea how to get this. If we would have this reference, we could call `validate()` immediately.

@wsmd Do you think that could work? Do you have any idea, how we could get a reference to the element?

**Comment by wsmd** [comment] 2019-04-28 00:12
Thanks for the issue @tdhung80.

Unfortunately this isn't possible _currently_ for the same exact reason @danielbuechele has explained above. Without an event target, which can only be accessed via the `change` and `blur` events, inputs cannot be validated.

>  Do you have any idea, how we could get a reference to the element?

The only way I can think of to make this happen is by using React's [refs](https://reactjs.org/docs/refs-and-the-dom.html). This would allow us to access the DOM nodes of inputs on mount without relying on events.

I started experimenting with this idea a while ago - it may be considered a breaking change so I have to think this through a bit more. It's definitely on the roadmap for future releases (hint: `v1.0.0`).

I'll look into this more in the next couple of weeks after I release `v0.10.0`.

That said, this might be a bit hacky, but maybe as a workaround for the time being, you could achieve this by building a custom validity object on mount and merge the results with the `formState.validity`.

I'm closing this issue _for now_ with a "future idea" label, but that doesn't mean we can't continue to chat about it. 🙂 

---

Note to self: duplicate of #47

**Closed** 2019-04-28 00:12 UTC
Labels: duplicate, future idea

**Comment by wsmd** [comment] 2019-04-28 00:14
This might be a bit hacky, but maybe as a workaround for the time being, you could achieve this by building a custom validity object on mount and merge the results with the `formState.validity`.

```js
// custom onMount input validator
function useOnMountInputValidator() {
  const [onMountValidity, setOnMountValidity] = React.useState({});

  const inputRefs = React.useRef({});

  const bind = React.useCallback(input => {
    if (input) {
      inputRefs.current[input.name] = input;
    }
  });

  React.useEffect(() => {
    for (const name in inputRefs.current) {
      setOnMountValidity(validity => ({
        ...validity,
        [name]: inputRefs.current[name].validity.valid
      }));
    }
  }, []);

  return {
    bind,
    validity: onMountValidity
  };
}

function App() {
  const [formState, input] = useFormState();
  const onMountValidator = useOnMountInputValidator();

  // final validity result including
  const validity = { ...onMountValidator.validity, ...formState.validity };
  return (
    <>
      <input {...input.text('name')} ref={onMountValidator.bind} required />
      <pre>{JSON.stringify(validity, null, 2)}</pre>
    </>
  );
}
```
